# ziye
# githubåœ°å€  https://github.com/6Svip120apk69
# TGé¢‘é“åœ°å€  https://t.me/ziyescript
# TGäº¤æµç¾¤    https://t.me/joinchat/AAAAAE7XHm-q1-7Np-tF3g
# boxjsé“¾æ¥   https://raw.githubusercontent.com/6Svip120apk69/gitee_q8qsTAUA_cThxc1RBVUE/main/Task/ziye.boxjs.json



# âš ï¸âš ï¸âš ï¸ç‰¹åˆ«é‡è¦,åŠ¡å¿…è¿›è¡Œæ›¿æ¢æ“ä½œï¼Œä¸å¾—ä½¿ç”¨åŸä½œè€…åœ°å€

# å…·ä½“æ–¹æ³•è¯·çœ‹: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions



#  ä»¥è´¦å·    aaa
#  ä»“åº“åœ°å€  https://github.com/aaa/bbb 
#  æ–‡ä»¶åœ°å€   https://raw.githubusercontent.com/aaa/bbb/ZIYE/Task/xiaole.js    ä¸ºä¾‹ 


# ä¸»è¦æ›¿æ¢çš„å­—ç¬¦ğŸ‘‡

# å°ä¹     //jsåå­—
# 0 0-15   //å®šæ—¶ï¼Œå¦‚åŒ—äº¬æ—¶é—´8åˆ°23ç‚¹ï¼Œè®¾ç½®0-15
# XL_URL   //ç¯å¢ƒå˜é‡ä¹‹ä¸€ï¼Œ47è¡Œå¤„è‡ªè¡Œæ·»åŠ å…¶ä»–
# aaa      //è´¦å·å
# bbb      //ä»“åº“å
# ZIYE     //åˆ†æ”¯å
# Task/xiaole.js  //å­æ–‡ä»¶åœ°å€




name: ç®€å•å¤©æ°”

on:
  workflow_dispatch:
  schedule:
     - cron: '10,40 0-14 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        JDTQ_jdtquserBODY: ${{ secrets.JDTQ_jdtquserBODY }}	
        JDTQ_jdtqcoinBODY: ${{ secrets.JDTQ_jdtqcoinBODY }}
        JDTQ_jdtqqpBODY: ${{ secrets.JDTQ_jdtqqpBODY }}
        JDTQ_jdtqqp1BODY: ${{ secrets.JDTQ_jdtqqp1BODY }}
        JDTQ_jdtqqp1fbBODY: ${{ secrets.JDTQ_jdtqqp1fbBODY }}
        JDTQ_jdtqqp2BODY: ${{ secrets.JDTQ_jdtqqp2BODY }}
        JDTQ_jdtqqp2fbBODY: ${{ secrets.JDTQ_jdtqqp2fbBODY }}
        JDTQ_jdtqqp3BODY: ${{ secrets.JDTQ_jdtqqp3BODY }}
        JDTQ_jdtqqp3fbBODY: ${{ secrets.JDTQ_jdtqqp3fbBODY }}
        JDTQ_jdtqqp4BODY: ${{ secrets.JDTQ_jdtqqp4BODY }}
        JDTQ_jdtqcjyBODY: ${{ secrets.JDTQ_jdtqcjyBODY }}
        JDTQ_jdtqcjBODY: ${{ secrets.JDTQ_jdtqcjBODY }}
        JDTQ_jdtqcjcsBODY: ${{ secrets.JDTQ_jdtqcjcsBODY }}
        JDTQ_jdtqrwBODY: ${{ secrets.JDTQ_jdtqrwBODY }}
        JDTQ_jdtqspBODY: ${{ secrets.JDTQ_jdtqspBODY }}
        JDTQ_jdtqspwcBODY: ${{ secrets.JDTQ_jdtqspwcBODY }}
        JDTQ_jdtqspwcfbBODY: ${{ secrets.JDTQ_jdtqspwcfbBODY }}
        JDTQ_jdtqqdBODY: ${{ secrets.JDTQ_jdtqqdBODY }}
        JDTQ_jdtqqdfbBODY: ${{ secrets.JDTQ_jdtqqdfbBODY }}
        JDTQ_jdtqqdwcBODY: ${{ secrets.JDTQ_jdtqqdwcBODY }}
        JDTQ_jdtqqdwcfbBODY: ${{ secrets.JDTQ_jdtqqdwcfbBODY }}
        JDTQ_jdtqtqBODY: ${{ secrets.JDTQ_jdtqtqBODY }}
        JDTQ_jdtqtqwcBODY: ${{ secrets.JDTQ_jdtqtqwcBODY }}
        JDTQ_jdtqtqwcfbBODY: ${{ secrets.JDTQ_jdtqtqwcfbBODY }}
        JDTQ_jdtqxfwcBODY: ${{ secrets.JDTQ_jdtqxfwcBODY }}
        JDTQ_jdtqxfwcfbBODY: ${{ secrets.JDTQ_jdtqxfwcfbBODY }}
        JDTQ_jdtqcfyBODY: ${{ secrets.JDTQ_jdtqcfyBODY }}
        JDTQ_jdtqcf1BODY: ${{ secrets.JDTQ_jdtqcf1BODY }}
        JDTQ_jdtqcf1fbBODY: ${{ secrets.JDTQ_jdtqcf1fbBODY }}
        JDTQ_jdtqcf2BODY: ${{ secrets.JDTQ_jdtqcf2BODY }}
        JDTQ_jdtqcf2fbBODY: ${{ secrets.JDTQ_jdtqcf2fbBODY }}
        JDTQ_jdtqcf3BODY: ${{ secrets.JDTQ_jdtqcf3BODY }}
        JDTQ_jdtqcf3fbBODY: ${{ secrets.JDTQ_jdtqcf3fbBODY }}
        JDTQ_jdtqcf4BODY: ${{ secrets.JDTQ_jdtqcf4BODY }}
        JDTQ_jdtqcf4BODY: ${{ secrets.JDTQ_jdtqcf4BODY }}
        JDTQ_jdtqcf4fbBODY: ${{ secrets.JDTQ_jdtqcf4fbBODY }}
        JDTQ_jdtqcf5BODY: ${{ secrets.JDTQ_jdtqcf5BODY }}
        JDTQ_jdtqcjyBODY: ${{ secrets.JDTQ_jdtqcjyBODY }}
        JDTQ_jdtqjcyBODY: ${{ secrets.JDTQ_jdtqjcyBODY }}
        JDTQ_jdtqjcaBODY: ${{ secrets.JDTQ_jdtqjcaBODY }}
        JDTQ_jdtqjcbBODY: ${{ secrets.JDTQ_jdtqjcbBODY }}
        JDTQ_jdtqjclqBODY: ${{ secrets.JDTQ_jdtqjclqBODY }}
        
        
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/208249775/AutoSyncScript.git ~/AutoSyncScript
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.JDTQ_jdtquserBODY
        run: |
          cd ~/AutoSyncScript
          git checkout ZIYE
          npm install
      - name: 'è¿è¡Œ ã€ç®€å•å¤©æ°”ã€‘'
        if: env.JDTQ_jdtquserBODY
        run: |
          cd ~/AutoSyncScript
          node Task/jdtq.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
